[build]
  publish = "dist"
  command = "npm run build"

[[redirects]]
  from = "https://userbase.dev/*"
  to = "https://userbase.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://www.userbase.dev/*"
  to = "https://userbase.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://userbase.netlify.com/*"
  to = "https://userbase.com/:splat"
  status = 301
  force = true

[[headers]]
  for = "/*"
  [headers.values]
    Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"